version: "3.7"
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  # webpacker:
  #   image: ${DOCKER_IMAGE_NAME-terrastories}
  #   command: ["./scripts/start_webpack_dev.sh"]
  #   volumes:
  #     - ./rails:/opt/terrastories:cached
  #   ports:
  #     - 3035:3035

  web:
    image: ${DOCKER_IMAGE_NAME-terrastories}
    build:
      context: ./rails
      args:
        precompileassets: "not"
    env_file:
      - .env
    links:
      - db
    ports:
      - 3000:3000
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_rails.sh"]
    volumes:
      - ./rails:/opt/terrastories:cached

  test-server:
    image: ${DOCKER_IMAGE_NAME-terrastories}
    build:
      context: ./rails
      args:
        precompileassets: "not"
    env_file:
      - .env
    environment:
      RAILS_ENV: test
    links:
      - db
    ports:
      - 3001:3000
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_test_server.sh"]
    volumes:
      - ./rails:/opt/terrastories:cached

  selenium:
    image: selenium/standalone-chrome-debug:3.0.1-germanium
      # Debug version enables VNC ability
    ports: ['4444:4444', '5900:5900']
      # Bind selenium port & VNC port
    logging:
      driver: none
      # Disable noisy logs.

  e2e:
    build:
      context: ./e2e
    volumes:
      - ./e2e:/opt/terrastories_e2e:cached
    environment:
      TEST_APP_HOST: test-server
      TEST_APP_PORT: 3001
      SELENIUM_HOST: selenium
      SELENIUM_PORT: 4444
    depends_on:
      - test-server
      - selenium

volumes:
  postgres_data:

